stages:
  - deploy

deploy:
  stage: deploy
  script:
    - git add .
    - git commit -m "pushed changes"
    - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
    - echo "Deployed to production server"
    