cache:
  paths:
    - node_modules/

stages:
  - install
  - build

install:
  stage: install
  image: node:latest 
  script:
    - npm install

build:
  stage: build
  image: node:latest
  script:
    - npm build

