stages:
  - deploy

deploy:
  stage: deploy
  script:
    - git push -f https://$HEROKU_USER:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD:master
    - echo "Deployed to production server"
  only:
   - master
    